###################################
# INSPYRENET SETTING
###################################
Model:
    name: "InSPyReNet_SwinB"
    depth: 64
    pretrained: True
    base_size: [1024, 1024]
    threshold: NULL

Train:
    Dataset:
        type: "RGB_Dataset"
        root: "data/Train_Dataset"
        sets: ['CUSTOM']
        transforms:
            static_resize: 
                size: [1024, 1024]
            random_scale_crop:
                range: [0.75, 1.25]
            random_flip:
                lr: True
                ud: False
            random_rotate:
                range: [-10, 10]
            random_image_enhance:
                methods: ['contrast', 'sharpness', 'brightness']
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        batch_size: 2
        shuffle: True
        num_workers: 8
        pin_memory: False
    Optimizer:
        type: "Adam"
        lr: 1.0e-07
        weight_decay: 0.0
        mixed_precision: False
    Scheduler:
        type: "PolyLr"
        epoch: 30
        gamma: 0.9
        minimum_lr: 1.0e-08
        warmup_iteration: 12000
    Checkpoint:
        checkpoint_epoch: 1
        checkpoint_dir: "/content/drive/MyDrive/InSPyRe_models"
    Debug:
        keys: ['saliency', 'laplacian']
    
Test:
    Dataset:
        type: "RGB_Dataset"
        root: "data/Test_Dataset"
        sets:  ['CUSTOM']
        transforms:
            # static_resize: 
            #     size: [1024, 1024]
            dynamic_resize:
                L: 1280
            tonumpy: NULL
            normalize: 
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
            totensor: NULL
    Dataloader:
        num_workers: 8
        pin_memory: True
    Checkpoint:
        checkpoint_dir: "snapshots/XBrain/v1"

Eval:
    gt_root: "data/Test_Dataset"
    pred_root: "snapshots/XBrain/v1"
    result_path: "results"
    datasets: ['CUSTOM']
    metrics: ['Sm', 'mae', 'avgIou', 'avgBIou', 'avgTIou', 'wFm', 'mBA']

###################################
# DEFAULT SETTING
###################################
onnx_model_root: "onnx"


###################################
# ONNX OPTIONS
###################################
omp_num_threads: null
